CREATE TYPE "public"."appointment_status" AS ENUM('agendada', 'realizada', 'cancelada', 'remarcada');--> statement-breakpoint
CREATE TYPE "public"."contact_submission_status" AS ENUM('novo', 'em_atendimento', 'arquivado');--> statement-breakpoint
CREATE TYPE "public"."message_direction" AS ENUM('inbound', 'outbound');--> statement-breakpoint
CREATE TYPE "public"."process_bucket" AS ENUM('andamento', 'acompanhamento', 'finalizado');--> statement-breakpoint
CREATE TYPE "public"."process_license_type" AS ENUM('LP', 'LI', 'LO', 'LAS', 'LMA', 'renovacao', 'outros');--> statement-breakpoint
CREATE TYPE "public"."process_status" AS ENUM('andamento', 'acompanhamento', 'finalizado', 'arquivado');--> statement-breakpoint
CREATE TYPE "public"."process_task_priority" AS ENUM('baixa', 'media', 'alta', 'urgente');--> statement-breakpoint
CREATE TYPE "public"."process_task_status" AS ENUM('aberta', 'em_andamento', 'aguardando_cliente', 'concluida', 'arquivada');--> statement-breakpoint
CREATE TYPE "public"."process_tipologia" AS ENUM('licenciamento', 'consultoria', 'laudo', 'monitoramento', 'outros');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('client', 'staff', 'admin');--> statement-breakpoint
CREATE TABLE "appointments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"process_id" uuid,
	"title" text,
	"description" text,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone,
	"status" "appointment_status" DEFAULT 'agendada' NOT NULL,
	"meet_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text,
	"entity_id" text,
	"before" jsonb,
	"after" jsonb,
	"at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "clients" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"notion_cnpj_filter" text,
	"notion_database_id" text,
	"notion_integration_token" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "contact_submissions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text,
	"email" text,
	"phone" text,
	"message" text,
	"status" "contact_submission_status" DEFAULT 'novo' NOT NULL,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_hash" text
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"process_id" uuid,
	"direction" "message_direction" NOT NULL,
	"from_addr" text,
	"to_addr" text,
	"subject" text,
	"body" text,
	"read" boolean DEFAULT false NOT NULL,
	"sent_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "process_license_types" (
	"process_id" uuid NOT NULL,
	"license_type" "process_license_type" NOT NULL,
	CONSTRAINT "process_license_types_process_id_license_type_pk" PRIMARY KEY("process_id","license_type")
);
--> statement-breakpoint
CREATE TABLE "process_milestone_kinds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"label_pt" text NOT NULL,
	"default_weight" integer DEFAULT 0 NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "process_milestone_kinds_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "process_milestones" (
	"process_id" uuid NOT NULL,
	"kind_id" uuid NOT NULL,
	"checked" boolean DEFAULT false NOT NULL,
	"checked_at" timestamp with time zone,
	"weight_override" integer,
	CONSTRAINT "process_milestones_process_id_kind_id_pk" PRIMARY KEY("process_id","kind_id")
);
--> statement-breakpoint
CREATE TABLE "process_tasks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"process_id" uuid NOT NULL,
	"notion_page_id" text,
	"title" text NOT NULL,
	"summary" text,
	"status" "process_task_status" DEFAULT 'aberta' NOT NULL,
	"priority" "process_task_priority" DEFAULT 'media' NOT NULL,
	"due_date" date,
	"assignee_user_id" uuid,
	"parent_task_id" uuid,
	"notion_synced_at" timestamp with time zone,
	"notion_etag" text,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "processes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" uuid NOT NULL,
	"code" text,
	"process_number" text,
	"name" text,
	"objective" text,
	"observation" text,
	"links" text,
	"status" "process_status" DEFAULT 'andamento' NOT NULL,
	"status_label" text,
	"tipologia" "process_tipologia",
	"responsible_tech_id" uuid,
	"city" text,
	"latitude" numeric,
	"longitude" numeric,
	"environmental_agency" text,
	"started_at" date,
	"due_date" date,
	"finished_at" date,
	"client_cnpj" text,
	"applicant_cnpj" text,
	"notion_page_id" text,
	"notion_synced_at" timestamp with time zone,
	"notion_etag" text,
	"notion_sync_errors" jsonb,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"display_name" text,
	"email" text,
	"role" "user_role" DEFAULT 'client' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "responsible_tech_aliases" (
	"responsible_tech_id" uuid NOT NULL,
	"notion_label" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "responsible_tech_aliases_responsible_tech_id_notion_label_pk" PRIMARY KEY("responsible_tech_id","notion_label")
);
--> statement-breakpoint
CREATE TABLE "responsible_techs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"display_name" text NOT NULL,
	"email" text,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "responsible_techs_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "user_clients" (
	"user_id" uuid NOT NULL,
	"client_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_clients_user_id_client_id_pk" PRIMARY KEY("user_id","client_id")
);
--> statement-breakpoint
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_process_id_processes_id_fk" FOREIGN KEY ("process_id") REFERENCES "public"."processes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_process_id_processes_id_fk" FOREIGN KEY ("process_id") REFERENCES "public"."processes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "process_license_types" ADD CONSTRAINT "process_license_types_process_id_processes_id_fk" FOREIGN KEY ("process_id") REFERENCES "public"."processes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "process_milestones" ADD CONSTRAINT "process_milestones_process_id_processes_id_fk" FOREIGN KEY ("process_id") REFERENCES "public"."processes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "process_milestones" ADD CONSTRAINT "process_milestones_kind_id_process_milestone_kinds_id_fk" FOREIGN KEY ("kind_id") REFERENCES "public"."process_milestone_kinds"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "process_tasks" ADD CONSTRAINT "process_tasks_process_id_processes_id_fk" FOREIGN KEY ("process_id") REFERENCES "public"."processes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "processes" ADD CONSTRAINT "processes_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "processes" ADD CONSTRAINT "processes_responsible_tech_id_responsible_techs_id_fk" FOREIGN KEY ("responsible_tech_id") REFERENCES "public"."responsible_techs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "responsible_tech_aliases" ADD CONSTRAINT "responsible_tech_aliases_responsible_tech_id_responsible_techs_id_fk" FOREIGN KEY ("responsible_tech_id") REFERENCES "public"."responsible_techs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_clients" ADD CONSTRAINT "user_clients_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "messages_client_sent_at_idx" ON "messages" USING btree ("client_id","sent_at");--> statement-breakpoint
CREATE UNIQUE INDEX "process_tasks_notion_page_id_uniq" ON "process_tasks" USING btree ("notion_page_id") WHERE deleted_at IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "processes_notion_page_id_uniq" ON "processes" USING btree ("notion_page_id") WHERE deleted_at IS NULL;